# Tensor
Tensor는 multi-dimensional array를 나타내는 말로, TensorFlow의 기본 data type

In [2]:
import tensorflow as tf
from tensorflow import keras

### Tensor 생성

``` python
tf.constant()
```

In [3]:
hello = tf.constant([3,3], dtype=tf.float32) # 출력에 .이 있으면 실수 아니면 정수
print(hello)

x= tf.constant([[1.,2.],[3.,4.]])
print(x)
print(type(x))

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### numpy or list를 tensor로 변환

``` python
tf.convert_to_tensor()
```

In [4]:
import numpy as np
x_np = np.array([[1.0,2.0],[3.0,4.0]])
x_list= [[1.,2.],[3.,4.]]
print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)
print(type(x_np))
print(type(x_list))


<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


#### 반대로 tensor를 numpy로 변경하기 

``` python
x_np.numpy()
```

In [6]:
x_np = x_np.numpy()
print(type(x_np))

<class 'numpy.ndarray'>


#### 반대로 tensor를 list로 변경하기 

``` python
x_list.__shape_as_list()
```

In [7]:
x_list= x_list._shape_as_list()
print(type(x_list))

<class 'list'>


# Tensor 틀 만들기


In [8]:
a = tf.ones((2,3))  # 1로 채우기
b = tf.zeros((2,3)) # 0으로 채우기
c = tf.fill((2,3),2.) # 원하는 숫자로 채우기

print(a)
print(b)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)


In [9]:
d = tf.zeros_like(c) # 크기랑 타입이 같고 원소는 0으로
e = tf.ones_like(c) # 크기랑 타입이 같고 원소는 1으로
print(d)
print(e)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
f= tf.eye(3) # 주대각 행렬만 1로 채울 때 사용
print(f)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
g = tf.range(10) # 연속된 값을 가진 Tensor , numpy에서는 arrange
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [12]:
h = tf.random.uniform((2,2)) # np.rand => 0~1의 균일 분포 표준정규분포 난수
i = tf.random.normal((2,2)) # np.randn => 평균은 0이고, 표준 편차 1의 가우시안 표준정규분포 난수
print(h)
print(i)

tf.Tensor(
[[0.37810588 0.49171174]
 [0.31835043 0.5530212 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.7340746   0.759347  ]
 [ 0.69351876  0.9866694 ]], shape=(2, 2), dtype=float32)


### Tensor의 속성

In [16]:
tensor = tf.random.normal((3,4))

print(tensor)
print(f"Shape of Tensor: {tensor.shape}")
print(f"Type of Tensor: {tensor.dtype}")

tf.Tensor(
[[ 0.26658162 -0.5148415   0.4194591  -1.5850695 ]
 [-0.13969456  0.8285318  -0.01659274  0.69209826]
 [ 1.792413    1.3026319   1.4027227   0.10454971]], shape=(3, 4), dtype=float32)
Shape of Tensor: (3, 4)
Type of Tensor: <dtype: 'float32'>


#### Tensor의 속성 변경

``` python
tf.reshape(origin, Size) # data의 size를 변경
tf.cast(origin, dtype)  # data type을 변경
```

In [17]:
tensor = tf.reshape(tensor,(4,3))
print(tensor)
print(f"Shape of Tensor: {tensor.shape}")
print(f"Type of Tensor: {tensor.dtype}")

tensor = tf.cast(tensor,tf.int32)
print(tensor)
print(f"Shape of Tensor: {tensor.shape}")
print(f"Type of Tensor: {tensor.dtype}")

tf.Tensor(
[[ 0.26658162 -0.5148415   0.4194591 ]
 [-1.5850695  -0.13969456  0.8285318 ]
 [-0.01659274  0.69209826  1.792413  ]
 [ 1.3026319   1.4027227   0.10454971]], shape=(4, 3), dtype=float32)
Shape of Tensor: (4, 3)
Type of Tensor: <dtype: 'float32'>
tf.Tensor(
[[ 0  0  0]
 [-1  0  0]
 [ 0  0  1]
 [ 1  1  0]], shape=(4, 3), dtype=int32)
Shape of Tensor: (4, 3)
Type of Tensor: <dtype: 'int32'>


### Variable 

variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 Tensor입니다.

딥러닝에서는 학습해야하는 가중치(weights, bias)들을 variable로 생성합니다.


In [20]:
tensor = tf.ones((3,4))
print(tensor)
tensor[0,0] = 2. # TENSOR 는 immutable

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [22]:
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [23]:
# 초기값을 사용해서 Variable을 생성할 수 있다.
initial_value = tf.random.normal(shape=(2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.05752413, -1.1927339 ],
       [-1.6496727 ,  1.9751338 ]], dtype=float32)>


In [24]:
# 한줄로 생성
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2,2)))
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.5128397 ,  1.8912162 ],
       [-0.20234832, -0.29292676]], dtype=float32)>


In [25]:
# variable은 .assign(value)나 .assign_add(increment), .assign_sub(decrement)와 같은 메소드를 사용해서 Variable 값을 갱신
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

tf.Tensor(
[[ 0.6286889  -0.5641703 ]
 [-0.75505555  0.4588442 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.6286889 , -0.5641703 ],
       [-0.75505555,  0.4588442 ]], dtype=float32)>


### Indexing과 Slicing


In [27]:
a= tf.range(1,13)
print(a)
a= tf.reshape(a,(3,4))
print(a)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
